### ISSUE TITLE
ListIpAddresses with usable filter does not exclude non-usable IPAddresses in Enumerator

### ISSUE THREAD

**Issue by JoostvdB94** [lduchosal/ipnetwork#124]
Tested with both

```
var cidrRange = "192.168.0.0/24"
var ipNetwork = IPNetwork.Parse(cidrRange);
var ipAddresses = ipNetwork.ListIPAddress(FilterEnum.Usable);

ipAddresses.Current // Gives 192.168.0.0
```
and
```
var cidrRange = "192.168.0.0/24"
var ipNetwork = IPNetwork.Parse(cidrRange);
var ipAddresses = ipNetwork.ListIPAddress(FilterEnum.Usable).AsEnumerable().GetEnumerator();

ipAddresses.Current // Gives 192.168.0.0
```

I have worked around this issue using a for-loop and the index accessor on the `IPAddressCollection`, but i would think this is not nessacary?

**Comment by lduchosal** [comment]
Thanks for your report, will check and fix this out.

**Comment by lduchosal** [comment]
Well, it looks like "Current" behaviour is right on purpose.

From the ienumerator documentation :

https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator.current?view=net-5.0

### Remarks
Current is undefined under any of the following conditions:

- The enumerator is positioned before the first element in the collection, immediately after the enumerator is created. **MoveNext must be called to advance the enumerator to the first element of the collection before reading the value of Current**.

- The last call to MoveNext returned false, which indicates the end of the collection.

- The enumerator is invalidated due to changes made in the collection, such as adding, modifying, or deleting elements.

- Current returns the same object until MoveNext is called. MoveNext sets Current to the next element.
