### ISSUE TITLE
Why is 10.0.0.0 parsed as 10.0.0.0/8?

### ISSUE THREAD

**Issue by viblo** [lduchosal/ipnetwork#28]
Today I noticed that if you dont specify the cidr block size it defaults to 8 bits when parsing IPNetworks. So for example `IPNetwork.Parse("78.12.137.223")` gives `78.0.0.0/8`. Is this intended? It feels like it would be more natural to parse it as `78.12.137.223/32`?

**Comment by fravelgue** [comment]
I think It's related to #22

**Comment by viblo** [comment]
Yes, seems like that. I tried to look it up before writing my question, but could not find any reference to which rfc that mentions this case.

**Comment by Deantwo** [comment]
It is because you didn't specify a network mask or CIDR. When no network mask or CIDR is specified in the `IPNetwork.Parse`, it will default to old classful netowrk mask, which in most cases make no sense. See what i wrote in #29 for details.

`IPNetwork` is used to make a IP network, not individual IP addresses. If you want to define a single IP address you should instead use `IPAddress`.

**Comment by lduchosal** [comment]
This implementation is based on the default behavior of Windows, Linux, BSD and mac when adding an IP address to a network interface:

```
ifconfig en4 10.0.0.2
-> inet 10.0.0.2 netmask 0xff000000 broadcast 10.255.255.255

ifconfig en4 172.17.1.1
-> inet 172.17.1.1 netmask 0xffff0000 broadcast 172.17.255.255

ifconfig en4 192.168.0.1
 -> inet 192.168.0.1 netmask 0xffffff00 broadcast 192.168.0.255

```
I did not find any RFC that would specify that this behavior is the desired behavior. 

If you need a /32, you might use IPAddress.Parse from base .NET that has this behavour.
Best regards
