### ISSUE TITLE
IPv6 defaults to 64 Cidr 

### ISSUE THREAD

**Issue by jfr8036** [lduchosal/ipnetwork#29]
Hi,
I was testing this package and came across this weird behavior:

```
var rangeToCheck = IPNetwork.Parse("2001:db8:abcd:0012:0000:0000:0000:0000/112");
var ipToCheck = IPNetwork.Parse("2001:db8:abcd:0012:0000:0000:0000:0001");

rangeToCheck.Contains(ipToCheck) == false;

```

is this a default ipv6 behavior or is this a bug? as far as I can debug, the "IpToCheck" defaults to cidr of 64 instead of 128.

Thanks

**Comment by Deantwo** [comment]
This done in the [`TryGuessCidr(string ip, out byte cidr)`](https://github.com/lduchosal/ipnetwork/blob/master/src/System.Net.IPNetwork/IPNetwork.cs#L1768) method, which attempts to find classful netmasks for IPv4 addresses. But since IPv6 was never classful this makes no sense for it. So someone seem to have picked /64 as the default CIDR for IPv6.
The exact line is here: [System.Net.IPNetwork/IPNetwork.cs#L1778](https://github.com/lduchosal/ipnetwork/blob/master/src/System.Net.IPNetwork/IPNetwork.cs#L1778).

I see no reference to there being a default CIDR for IPv6, but /64 seem to be mentioned a lot in documention and preferred by most. So this does make sense as a default CIDR.

I think the real issue here is that most network engineers would assume that a IP address with no network mask or CIDR is always a single IP address and not an IP network, so therefore /32 for IPv4 and /128 for IPv6 makes more sense.

The code in the opening post should have been written as:
``` C#
IPNetwork rangeToCheck = IPNetwork.Parse("2001:db8:abcd:0012:0000:0000:0000:0000/112");
IPAddress ipToCheck = IPAddress.Parse("2001:db8:abcd:0012:0000:0000:0000:0001");

rangeToCheck.Contains(ipToCheck) == false;
```
As shown in [Example 2 (IPv6)](https://github.com/lduchosal/ipnetwork/blob/master/README.md#example-2-ipv6-) of the ReadMe.

**Comment by lduchosal** [comment]
This seem like a default behaviour in standard tools.

Have a look at  [af_inet6.c](https://github.com/freebsd/freebsd/blob/master/sbin/ifconfig/af_inet6.c) for IPV6.

static void
in6_postproc(int s, const struct afswtch *afp)
{
	if (explicit_prefix == 0) {
		/* Aggregatable address architecture defines all prefixes
		   are 64. So, it is convenient to set prefixlen to 64 if
		   it is not specified. */
		setifprefixlen("64", 0, s, afp);
		/* in6_getprefix("64", MASK) if MASK is available here... */
	}
}
