### ISSUE TITLE
First usable and last usable ip not calculated correctly.

### ISSUE THREAD

**Issue by jbrnsk** [lduchosal/ipnetwork#54]
The first and last usable ip values do no appear to be calculated correctly. According to [Wikipedia](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing), a 31-bit CIDR should have two usable addresses.

**### Example 1**

**Entered cidr value:**
10.2.2.3/31

**Range returned by this [mxtoolbox calculator:](https://mxtoolbox.com/subnet/?filter=10.2.2.2/31&source=subnettool)** 
10.3.3.2 - 10.3.3.3

**Number of addresses from toolbox:** 
2 - definitely correct according to Wikipedia ^

**Range returned by this ipnetwork package:** 
10.2.2.2 - 10.2.2.2

**Number of addresses from ipnetwork:** 
1 - incorrect

**### Example 2**

**Entered cidr value:**
10.2.2.3/27

**Range returned by this [mxtoolbox calculator:](https://mxtoolbox.com/subnet/?filter=10.2.2.0/27&source=subnettool)** 
10.2.2.0 - 10.2.2.31

**Number of addresses from toolbox:** 
32

**Range returned by the ipnetwork package:** 
10.2.2.1 - 10.2.2.30

**Number of addresses from ipnetwork:** 
30

**Comment by jbrnsk** [comment]
This is a custom solution that I implemented for now to calculate those fields. Maybe this project should be doing something similar. 

Note that for our purposes we don't want first usable address to ever end in a 0.  I'm not sure that you would want to apply that extra piece of logic.

`
  string cidrNotation = '10.13.13.3/31' <--Something the user inputted

   if (IPNetwork.TryParse(cidrNotation, out IPNetwork ipNetwork))
   {
        String[] cidrNotationArray = cidrNotation.Split("/");
              
        String baseUrl = cidrNotationArray?.Length > 1 ? cidrNotationArray.First() : string.Empty;

        // Here we have some unrelated code that we perform on ipNetwork
        // etc.
        // etc.

        // Pertinent part:
        byte[] ipBytes = baseUrl.GetAddressBytes();
        byte[] maskBytes = ipNetwork.Netmask.GetAddressBytes();

        byte[] startIpBytes = new byte[ipBytes.Length];
        byte[] endIpBytes = new byte[ipBytes.Length];

        for (var i = 0; i < ipBytes.Length; i++)
        {
               byte startByteValue = (byte)(ipBytes[i] & maskBytes[i]);
               byte endByteValue = (byte)(ipBytes[i] | ~maskBytes[i]);

                // Last byte value in start array cannot end in 0 as this is a base address, make it 1 instead
                startIpBytes[i] = i == (ipBytes.Length - 1) && startByteValue == 0 ? (byte)1 : startByteValue; 
                 endIpBytes[i] = endByteValue;
         }

          IPAddress FirstUsable = new IPAddress(startIpBytes);
          IPAddress LastUsable = new IPAddress(endIpBytes);

         // etc.
   }   
  
`

**Comment by lduchosal** [comment]
**Exemple 1**
> ipnetwork.exe 10.2.2.3/31

```
IPNetwork   : 10.2.2.2/31
Network     : 10.2.2.2
Netmask     : 255.255.255.254
Cidr        : 31
Broadcast   : 10.2.2.3
FirstUsable : 10.2.2.2
LastUsable  : 10.2.2.2
Usable      : 0
Total       : 2
```
 The maximum number of network ID bits is 30. You have to leave at least two bits for the host ID portion of the address, to allow for at least two hosts. If you used all 32 bits for the network ID, that would leave no bits for the host ID. Obviously, that doesn’t work. Leaving just one bit for the host ID doesn’t work, either. That’s because a host ID of all ones is reserved for a broadcast address — and all zeros refers to the network itself. 

Thus, if you used 31 bits for the network ID and left only one for the host ID, host ID 1 would be used for the broadcast address and host ID 0 would be the network itself, leaving no room for actual hosts. That’s
why the maximum network ID size is 30 bits.

http://www.nortonaudio.com/Ficheiros/1118474082.Netwo.pdf

**Example 2**

> ipnetwork.exe 10.2.2.3/27

```
IPNetwork   : 10.2.2.0/27
Network     : 10.2.2.0
Netmask     : 255.255.255.224
Cidr        : 27
Broadcast   : 10.2.2.31
FirstUsable : 10.2.2.1
LastUsable  : 10.2.2.30
Usable      : 30
Total       : 32
```

This example doesn't conflict with mxtoolbox neither.
The range is Network ID to Broadcast    10.2.2.0 - 10.2.2.31, total 32
The usable, assignable range is 10.2.2.1 - 10.2.2.30, total 30

**Comment by jbrnsk** [comment]
Okay, I understand now. I appreciate the detailed response!
